app/controllers/jobs_controller.rb
config/routes.rb
test/controllers/jobs_controller_test.rb

controller

---

app/controllers/jobs_controller.rb
app/views/jobs/_form.html.erb

controller_create

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_kanban.scss
app/controllers/application_controller.rb
app/models/user.rb
app/views/jobs/_kanban.html.erb
app/views/jobs/index.html.erb
app/views/jobs/new.html.erb
app/views/layouts/application.html.erb
db/migrate/20230228233555_add_avatar_to_user.rb
db/schema.rb

Added front end kanban, to start coding js and have ideas done, added avatar to dependencies to start cloudinary deploy, removed unused gem.

added kanban front, removed unused gems

---

app/assets/stylesheets/components/_kanban.scss
app/views/devise/registrations/edit.html.erb
app/views/jobs/_kanban.html.erb
db/migrate/20230301130048_create_active_storage_tables.active_storage.rb
db/schema.rb

Delete account fixed, need to install active storage.
Fixed css conflicts between kanban style and devise style.

fixed delete account, fixed css in conflict

---

app/views/devise/registrations/new.html.erb
app/views/shared/_navbar.html.erb

Devise and navbar sign out done, added same naming in both pages at the front end, backend working, sign out send user to landing page.

Devise and navbar sign out done

---

.gitignore

added dotenv-rails

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/shared/_navbar.html.erb
config/environments/development.rb
config/environments/production.rb
config/storage.yml

Avatar for user edit page and for index page done, if avatar is not added, an random picutre from assets is added

avatar done

---

app/assets/stylesheets/components/_kanban.scss
app/views/jobs/_kanban.html.erb

kanban front

---

app/views/jobs/_kanban.html.erb

new push to help team

---

app/views/devise/registrations/edit.html.erb
app/views/jobs/index.html.erb

fixed placeholder edit devise

---

app/javascript/controllers/application.js
app/javascript/controllers/hello_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/job_controller.js
app/views/jobs/_kanban.html.erb
app/views/jobs/_modal.html.erb
app/views/jobs/index.html.erb
package.json
yarn.lock

Firsta Stimulus feature:
Add a <li> elemente with new card name in the card at kanban board.
Added a test modal, disabled in the kanban board. to refactor for future use to insert in the <li> element the data came from the job form or the scrap in the near future if possible.

stimulus first feature add a new list in card

---

app/views/jobs/show.html.erb

still need to do the front-end part

back - show

---

app/views/devise/registrations/new.html.erb
app/views/jobs/index.html.erb
db/schema.rb

removed login from sign up

---

app/controllers/jobs_controller.rb

controller update

---

app/assets/stylesheets/components/_kanban.scss
app/views/jobs/_kanban.html.erb
app/views/jobs/_modal.html.erb
app/views/jobs/index.html.erb
app/views/layouts/application.html.erb

mudancas front end

---

app/controllers/application_controller.rb
app/javascript/controllers/job_controller.js
app/views/pages/_banner.html.erb

added after sign up redirect, added more functions to stimulus

added after sign up redirect, added more functions to stimulus

---

app/views/columns/_kanban.html.erb

just changed add a card to add note

refrase kanaban

---

app/assets/stylesheets/components/_sortable.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/controllers/index.js
app/javascript/controllers/sortable_controller.js
app/views/pages/home.html.erb
package.json
yarn.lock

button color and h2 normalization

button color and h2 normalization

---

app/assets/stylesheets/components/_kanban.scss

Removed bullets form lists when it is created in columns page

remove li bullets

---

Gemfile
Gemfile.lock
app/javascript/controllers/job_controller.js
app/views/columns/_kanban.html.erb
config/routes.rb

add icon to add form to kanban, add icon to add list

add icon to add form to kanban, add icon to add list

---

app/assets/stylesheets/components/_kanban.scss
app/assets/stylesheets/components/_navbar.scss
app/javascript/controllers/job_controller.js
app/views/columns/_kanban.html.erb
app/views/shared/_navbar.html.erb

Changed names for icons in kanban,
Minor changes in front end.

changes in front end

---

app/views/columns/_kanban.html.erb

Arrumado conflitos entre o kanban view da Taisa com a feature search, e o kanbam do Luiz com a feature sortable.

fixed problems in front

---

app/javascript/controllers/sortable_controller.js
db/schema.rb

continuacao sortable part 5

---

app/assets/stylesheets/components/_kanban.scss
app/assets/stylesheets/pages/_kanban.scss
app/controllers/jobs_controller.rb
app/views/columns/_kanban.html.erb
app/views/jobs/_form_new.html.erb
app/views/jobs/_job.html.erb
yarn.lock

Added style to Add c card button and edit a card, as fontawesome buttons with hover.
Added position for both buttons.
Fixed edit route of kanban card and its message.

front end kanban

---

app/assets/stylesheets/components/_kanban.scss
app/assets/stylesheets/components/_navbar.scss
app/views/columns/_kanban.html.erb
app/views/shared/_navbar.html.erb

frontendless
Display inline search tags with search input, and added the same size for both.
Added Sign Up to home page and displayed inline to login.
Added the proper css.

frontendless

---

app/views/shared/_navbar.html.erb

calendar button

---

app/views/columns/_kanban.html.erb

adiconado o maiszinho

---

app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/components/_index.scss
app/controllers/calendar_events_controller.rb
app/models/calendar_event.rb
app/models/meeting.rb
app/policies/calendar_event_policy.rb
app/views/simple_calendar/_calendar.html.erb
app/views/simple_calendar/_month_calendar.html.erb
app/views/simple_calendar/_week_calendar.html.erb
config/routes.rb
db/migrate/20230314214838_create_meetings.rb
db/migrate/20230314222717_remove_meeting.rb
db/migrate/20230314230130_remove_job_from_calendar_event.rb
db/schema.rb
test/controllers/calendar_events_controller_test.rb
test/models/meeting_test.rb

updating calendar

---

app/views/columns/_kanban.html.erb
db/seeds.rb

fix taisa code

---

app/assets/stylesheets/pages/_kanban.scss
app/controllers/jobs_controller.rb
app/javascript/controllers/sortable_controller.js
app/views/columns/_kanban.html.erb
app/views/jobs/_job.html.erb

frontendless + sortable in progress

frontendless + sortable in progress

---

app/javascript/controllers/sortable_controller.js
app/views/jobs/_job.html.erb

sortable quase terminado
Funcionando as funções do modal, do search e do sortable em conjunto, falta posição correta e ir de baixo para cima.

sortable quase terminado

---

app/assets/stylesheets/components/_kanban.scss
app/assets/stylesheets/pages/_kanban.scss
app/javascript/controllers/application.js
app/javascript/controllers/dark_light_controller.js
app/javascript/controllers/index.js
app/views/columns/_kanban.html.erb

dark-light-mode

---

app/javascript/controllers/dark_light_controller.js
app/views/columns/_kanban.html.erb

dark-mode-done

---

Gemfile
Gemfile.lock
app/controllers/jobs_controller.rb
app/javascript/controllers/sortable_controller.js
app/models/job.rb
app/views/devise/registrations/new.html.erb
app/views/jobs/_job.html.erb

sortable parte 7

---

app/controllers/jobs_controller.rb
app/javascript/controllers/sortable_controller.js

sortable movendo

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_kanban.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_kanban.scss
app/views/devise/registrations/new.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Added Colors to config variables.
Starting change in the code to apply the colors by $bootstrap variables

start front end style

---

app/assets/stylesheets/components/_kanban.scss

frontendless part 1001

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button_orange.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_dashboard.scss

frontendless part 1002

---

app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/components/_index.scss
app/views/calendar_events/new.html.erb
app/views/simple_calendar/_month_calendar.html.erb
db/seeds.rb

frontendless calendar

---

app/views/columns/_kanban.html.erb
app/views/simple_calendar/_month_calendar.html.erb

front calendar
+
Fixes Savannes codes

front calendar

---

app/views/columns/_kanban.html.erb
app/views/jobs/_job.html.erb

more front finishes

---

app/assets/stylesheets/components/_kanban.scss
app/assets/stylesheets/pages/_devise.scss
app/assets/stylesheets/pages/_index.scss
app/javascript/controllers/hello_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/sortable_controller.js
app/views/columns/_kanban.html.erb
app/views/devise/sessions/new.html.erb
package-lock.json
package.json
webpack.config.js
yarn.lock

sortable sorting draggin
other minor changes
trying to add a background image to login and sign up

sortable sorting draggin

---

app/assets/stylesheets/pages/_devise.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

devise imgs working in progress

devise imgs

---

app/views/calendar_events/new.html.erb
app/views/calendars/index.html.erb
db/migrate/20230321235246_remove_default_from_name.rb
db/schema.rb
yarn.lock

last_update calendar

---

app/javascript/controllers/sortable_controller.js

js fix in course

---

app/javascript/controllers/sortable_controller.js

Sortable working, drag, drop, save state to current user.
Modal edit and delete working.
Need to fix console errors.

Sortable Kanban Modal fix part 1

---

app/javascript/controllers/sortable_controller.js
app/views/columns/_kanban.html.erb

sortable fixed, all working
era so colocar o sortable controller no view, em uma div, fora da ul!!!!!

sortable fixed, all working

---

app/views/columns/_kanban.html.erb
yarn.lock

retornei codigo antigo do sortable, parou de funcionar

retornei codigo antigo do sortable, parou de funcionar

---

app/assets/stylesheets/pages/_kanban.scss
app/javascript/controllers/dark_light_controller.js

add dark light button css
and function in js

add dark light button css
